name: Scrape Twitter
on:
  schedule:
    - cron: "0 * * * *"   # run every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install snscrape
      - run: python tools/scrape_twitter.py
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          if ! git diff --cached --quiet; then
            git commit -m "Update cached tweets [skip ci]"
            git push
          else
            echo "No new tweets"
          fi
